"""Protocol defining the shared interface for capture file readers."""

from typing import Optional, Protocol, runtime_checkable

import pandas as pd


@runtime_checkable
class CaptureReader(Protocol):
    """Protocol for capture file readers (Kismet DB, PCAP, etc.)."""

    def open_database(self, path: str) -> bool: ...
    def close_database(self) -> None: ...
    def is_connected(self) -> bool: ...
    def get_database_info(self) -> dict: ...
    def get_device_summary(self) -> dict: ...
    def get_access_points(self, filters: Optional[dict] = None) -> pd.DataFrame: ...
    def get_clients(self, filters: Optional[dict] = None) -> pd.DataFrame: ...
    def get_all_devices(self, filters: Optional[dict] = None) -> pd.DataFrame: ...
    def get_bluetooth_devices(self, filters: Optional[dict] = None) -> pd.DataFrame: ...
    def get_networks(self) -> pd.DataFrame: ...
    def get_gps_data(self) -> pd.DataFrame: ...
    def get_device_gps_track(self, devmac: str) -> pd.DataFrame: ...
    def get_data_sources(self) -> pd.DataFrame: ...
    def get_alerts(self) -> pd.DataFrame: ...
    def get_packets_timeline(self) -> pd.DataFrame: ...
    def get_signal_distribution(self) -> pd.DataFrame: ...

    # PCAP-specific methods (Kismet reader returns empty defaults)
    def get_handshakes(self) -> pd.DataFrame: ...
    def get_deauth_frames(self) -> pd.DataFrame: ...
    def get_probe_requests(self) -> pd.DataFrame: ...
    def get_frame_type_distribution(self) -> pd.DataFrame: ...
    def has_pcap_features(self) -> bool: ...
